val:
  _target_: src.datasets.AlignerDataset
  name: "val"
  # instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.AlignerDataset
  name: "test"
  # instance_transforms: ${transforms.instance_transforms.inference}
