train:
  - _target_: src.datasets.AlignerDataset
    # instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.AlignerDataset
  name: "val"
test:
  _target_: src.datasets.AlignerDataset
  name: "test"
